stages:
    - build
    - docker
        
job_build_dotnet:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - export PROJECT_NAME=Recount.Console\\Recount.Console.csproj
        - dotnet restore
        - dotnet build $PROJECT_NAME
        
job_build_docker:
       stage: docker
       image: docker:latest
       script:
        - docker login registry.gitlab.com
        - docker build -t registry.gitlab.com/ivatkoegor/recount .
        - docker push registry.gitlab.com/ivatkoegor/recount
       dependencies:
        - job_build_dotnet
        
      