stages:
    - build
    - docker

job_build_dotnet:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - dotnet restore Recount.Web\\Recount.Web.csproj
        - dotnet build Recount.Web\\Recount.Web.csproj
        
job_build_docker:
       stage: docker
       image: docker:latest
       services:
        - docker:dind
       script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/snuk/recount/recount.web .
        - docker push registry.gitlab.com/snuk/recount/recount.web
       dependencies:
        - job_build_dotnet
        
      