stages:
    - build
        
job_build_dotnet:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - export PROJECT_NAME=Recount.Console\Recount.Console.csproj
        - dotnet restore
        - dotnet build $PROJECT_NAME
      